import { Inter } from 'next/font/google'
import './global.css';
import Header from './Header';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next My Page App',
  description: 'Generated by create next app',
}
//Master layout for gobal page
export default function RootLayout({ children }) {
  return (
    
    <html>
      <Header />
      <body className={inter.className}>{children}</body>
    </html>
    
  )
}
